
// Login mit Basic Authentication mit korrekten Credentials admin:123
###
# @name loginAdminCorrect
GET https://localhost/api/authenticate
Authorization: Basic YWRtaW46MTIz

@adminToken = {{loginAdminCorrect.response.headers.Authorization}}

// Lege zweiten User an
###
POST https://localhost/api/testusers
Content-Type: application/json

{
    "userID": "manfred",
    "email": "s87771@bht-berlin.de",
    "firstName": "Manfred",
    "lastName": "Müller",
    "password": "asdf"
}

###
GET https://localhost/api/testusers
Authorization: {{adminToken}}

###
GET https://localhost/api/activation/uoKvcC7