// Token für admin erzeugen
###
POST http://localhost/api/authenticate
Content-Type: application/json

{
    "userID": "admin",
    "password": "123"
}

// Token für manfred erzeugen
###
POST http://localhost/api/authenticate
Content-Type: application/json

{
    "userID": "manfred",
    "password": "asdf"
}

// Login mit Basic Authentication als admin mit korrekten Credentials admin:123
###
# @name loginAdminCorrect
GET http://localhost/api/authenticate
Authorization: Basic YWRtaW46MTIz

// Login mit Basic Authentication als admin mit falschen Credentials
// Hinweis: Der REST-Client überführt das Passwort automatisch nach Base64
###
GET http://localhost/api/authenticate
Authorization: Basic admin:asdf

@adminToken = {{loginAdminCorrect.response.headers.Authorization}}

### Auflisten aller Nutzer, ohne dass ein Token übergeben wird --> Anfrage scheitert mit 401 
http://localhost/api/users

### Auflisten aller Nutzer mit Token von admin
http://localhost/api/users
Authorization: {{adminToken}}

### Auflisten aller Nutzer mit dem manfred-Token
GET http://localhost/api/users
Authorization: {{manfredToken}}

### Lege neuen user manfred an
POST http://localhost/api/users
Authorization: {{adminToken}}
Content-Type: application/json

{
    "userID": "manfred",
    "firstName": "Manfred",
    "lastName": "Mustermann",
    "password": "asdf"
}

### Abrufen des angelegten Users mit dem Admin-Token
GET http://localhost/api/users/manfred
Authorization: {{adminToken}}

### Abrufen des User sich selbst mit seinem Token
GET http://localhost/api/users/manfred
Authorization: {{manfredToken}}

// Ändere beim zweiten User den User-Name. Zur Selektion des Users verwende die userID.
###
PUT http://localhost/api/users/manfred
Content-Type: application/json
Authorization: {{manfredToken}}

{
    "firstName": "Sandraass",
    "lastName": "SMeierrs"
}

// Login mit Basic Authentication als manfred mit korrekten Credentials
###
# @name loginManfredCorrect
GET http://localhost/api/authenticate
Authorization: Basic manfred:asdf

@manfredToken = {{loginManfredCorrect.response.headers.Authorization}}

### Auflisten aller Nutzer mit Token von manfred, das sollte nicht möglich sein
GET http://localhost/api/users
Authorization: {{adminToken}}

### Auflisten aller Studiengänge
GET http://localhost/api/degreeCourses
Authorization: {{manfredToken}}

// Lege einen Studiengang an
###
# @name createDegreeCourseRequest
POST http://127.0.0.1/api/degreeCourses
Authorization: {{adminToken}}
Content-Type: application/json

{
    "universityName": "Beuth Haochschule für Technik bbBerlin",
    "universityShortName": "Besuth HS",
    "departmentName": "Informatik und Medien",
    "departmentShortName": "FB VI",
    "name": "Orchideenzucht Bachelor",
    "shortName": "OZ-BA"
}

###
@degreeCourseID = {{createDegreeCourseRequest.response.body.id}}

### Auflisten aller Studiengänge, es sollte jetzt einen geben
http://localhost/api/degreeCourses
Authorization: {{adminToken}}
###
POST http://localhost/api/degreeCourses
Authorization: {{adminToken}}
Content-Type: application/json

{
    "id": "WE2-TestDB-d4872søe-7957-4356-ae94-15bd69øed823",
    "name": "Orchideenzucht Bachelor",
    "shortName" : "OZ-BA",
    "universityName": "Beuth Hochschule für Technik Berlin" ,
    "universityShortName": "Beuth HS",
    "departmentName": "Beuth Hochschule für Technik Berlin" ,
    "departmentShortName": "Beuth HS" 
}

### Abrufen von dem angelegten Studiengang
http://localhost/api/degreeCourses/WE2-TestDB-d4872søe-7957-4356-ae94-15bd69øed823
Authorization: {{adminToken}}


### Ändere den Namen des Studiengangs
PUT http://localhost/api/degreeCourses/WE2-TestDB-d4872søe-7957-4356-ae94-15bd69øed823
Authorization: {{adminToken}}
Content-Type: application/json

{
    "name": "Tulpenzucht"
}

###
POST http://localhost/api/degreeCourses
Authorization: {{adminToken}}
Content-Type: application/json

{
    "id": "WE2-TestDB-d4872søe-7957-4356-ae94-15bd69øed823",
    "name": "Orchideenzucht Bachelor",
    "shortName" : "OZ-BA",
    "universityName": "HTW Hochschule für Technik Berlin" ,
    "universityShortName": "HTW HS",
    "departmentName": "HTW Hochschule für Technik Berlin" ,
    "departmentShortName": "HTW" 
}

### Auflisten der Studiengänge einer bestimmten Hochschule
GET http://localhost/api/degreeCourses?universityShortName=Beuth HS
Authorization: {{adminToken}}

### Auflisten der Studiengänge einer bestimmten Hochschule
GET http://localhost/api/degreeCourses?universityShortName=HTW HS
Authorization: {{adminToken}}


### Auflisten aller Studiengänge, es sollte jetzt einen geben
http://localhost/api/degreeCourses
Authorization: {{adminToken}}

### Lösche den angelegten Studiengang
DELETE http://localhost/api/degreeCourses/WE2-TestDB-d4872søe-7957-4356-ae94-15bd69øed823
Authorization: {{adminToken}}

### Lösche den User manfred
DELETE http://localhost/api/users/manfred
Authorization: {{adminToken}}